# Generated by Django 5.2.8 on 2025-11-26 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('remaining_positions', models.IntegerField()),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_no', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('S', 'Staff'), ('U', 'User')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('media_no', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('I', 'Image'), ('V', 'Video'), ('D', 'Document')], max_length=1)),
                ('upload_date', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('AR', 'Archived'), ('I', 'Inactive')], max_length=2)),
                ('product_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='booking.product')),
            ],
            options={
                'db_table': 'media_files',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_no', models.AutoField(primary_key=True, serialize=False)),
                ('subscriber_category', models.CharField(choices=[('T', 'Trainer'), ('C', 'Customer'), ('V', 'VIP')], max_length=1)),
                ('product_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='booking.product')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='booking.user')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_no', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.user')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_no', models.AutoField(primary_key=True, serialize=False)),
                ('booking_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='booking.booking')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='booking.user')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
