# Generated by Django 5.2.8 on 2025-12-10 22:49

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('year_of_birth', models.IntegerField(default=2000)),
                ('height_in_cm', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('bookingstart_time', models.TimeField()),
                ('bookingend_time', models.TimeField()),
                ('booking_capacity', models.IntegerField(default=0)),
                ('booking_remaining', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='bookings_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appusersNo', models.ForeignKey(on_delete=builtins.all, to='authentication.appusers')),
                ('bookingsNo', models.ForeignKey(on_delete=builtins.all, to='authentication.bookings')),
            ],
        ),
    ]
