# Generated by Django 4.2.23 on 2025-11-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile_phone',
            field=models.CharField(default=123456789, max_length=15),
            preserve_default=False,
        ),
    ]
