# Generated by Django 4.2.23 on 2025-11-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_users_first_name_alter_users_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
