# Generated by Django 4.2.23 on 2025-11-26 22:56

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_appusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('bookingstart_time', models.TimeField()),
                ('bookingend_time', models.TimeField()),
                ('booking_capacity', models.IntegerField(default=0)),
                ('booking_remaining', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='appusers',
            name='height_in_cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appusers',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='appusers',
            name='year_of_birth',
            field=models.IntegerField(default=2000),
        ),
        migrations.CreateModel(
            name='bookings_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appusersNo', models.ForeignKey(on_delete=builtins.all, to='authentication.appusers')),
                ('bookingsNo', models.ForeignKey(on_delete=builtins.all, to='authentication.bookings')),
            ],
        ),
    ]
