# Generated by Django 6.0 on 2026-01-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerprofile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='certifications',
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='professional_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_pic_for', to='files.file'),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
