# Generated by Django 6.0 on 2026-01-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_rename_phone_number_trainerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
